//     open-dis-rust - Rust implementation of the IEEE-1278.1 Distributed Interactive Simulation
//     Copyright (C) 2023 Cameron Howell
//
//     Licensed under the BSD-2-Clause License

use num_derive::FromPrimitive;

// SISO-REF-010-2023 Protocol Version [UID 3]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
#[allow(non_camel_case_types)]
pub enum ProtocolVersion {
    #[default]
    Other = 0,
    DIS_PDUv1 = 1,
    IEEE1278_1993 = 2,
    DIS_PDUv2_Third_Draft = 3,
    DIS_PDUv2_Fourth_Draft_Revised = 4,
    IEEE1278_1_1995 = 5,
    IEEE1278_1A_1998 = 6,
    IEEE1278_1_2012 = 7,
}

// SISO-REF-010-2023 PDU Type [UID 4]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum PduType {
    #[default]
    Other = 0,
    EntityState = 1,
    Fire = 2,
    Detonation = 3,
    Collision = 4,
    ServiceRequest = 5,
    ResupplyOffer = 6,
    ResupplyReceived = 7,
    ResupplyCancel = 8,
    RepairComplete = 9,
    RepairResponse = 10,
    CreateEntity = 11,
    RemoveEntity = 12,
    StartResume = 13,
    StopFreeze = 14,
    Acknowledge = 15,
    ActionRequest = 16,
    ActionResponse = 17,
    DataQuery = 18,
    SetData = 19,
    Data = 20,
    EventReport = 21,
    Comment = 22,
    ElectromagneticEmission = 23,
    Designator = 24,
    Transmitter = 25,
    Signal = 26,
    Receiver = 27,
    IFF = 28,
    UnderwaterAcoustic = 29,
    SupplementalEmission = 30,
    IntercomSignal = 31,
    IntercomControl = 32,
    AggregateState = 33,
    IsGroupOf = 34,
    TransferOwnership = 35,
    IsPartOf = 36,
    MinefieldState = 37,
    MinefieldQuery = 38,
    MinefieldData = 39,
    MinefieldResponseNack = 40,
    EnvironmentalProcess = 41,
    GriddedData = 42,
    PointObjectState = 43,
    LinearObjectState = 44,
    ArealObjectState = 45,
    TSPI = 46,
    Appearance = 47,
    ArticulatedParts = 48,
    LEFire = 49,
    LEDetonation = 50,
    CreateEntityReliable = 51,
    RemoveEntityReliable = 52,
    StartResumeReliable = 53,
    StopFreezeReliable = 54,
    AcknowledgeReliable = 55,
    ActionRequestReliable = 56,
    ActionResponseReliable = 57,
    DataQueryReliable = 58,
    SetDataReliable = 59,
    DataReliable = 60,
    EventReportReliable = 61,
    CommentReliable = 62,
    RecordReliable = 63,
    SetRecordReliable = 64,
    RecordQueryReliable = 65,
    CollisionElastic = 66,
    EntityStateUpdate = 67,
    DirectedEnergyFire = 68,
    EntityDamageStatus = 69,
    InformationOperationsAction = 70,
    InformationOperationsReport = 71,
    Attribute = 72,
}

// SISO-REF-010-2023 Protocol Family [UID 5]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum ProtocolFamily {
    #[default]
    Other = 0,
    EntityInformation = 1,
    Warfare = 2,
    Logistics = 3,
    RadioCommunications = 4,
    SimulationManagement = 5,
    DistributedEmissionRegeneration = 6,
    EntityManagement = 7,
    Minefield = 8,
    SyntheticEnvironment = 9,
    SimulationManagementWithReliability = 10,
    LiveEntityInformationInteraction = 11,
    NonRealTime = 12,
    InformationOperations = 13,
}

// SISO-REF-010-2023 Force ID [UID 6]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum ForceId {
    #[default]
    Other = 0,
    Friendly = 1,
    Opposing = 2,
    Neutral = 3,
    Friendly2 = 4,
    Opposing2 = 5,
    Neutral2 = 6,
    Friendly3 = 7,
    Opposing3 = 8,
    Neutral3 = 9,
    Friendly4 = 10,
    Opposing4 = 11,
    Neutral4 = 12,
    Friendly5 = 13,
    Opposing5 = 14,
    Neutral5 = 15,
    Friendly6 = 16,
    Opposing6 = 17,
    Neutral6 = 18,
    Friendly7 = 19,
    Opposing7 = 20,
    Neutral7 = 21,
    Friendly8 = 22,
    Opposing8 = 23,
    Neutral8 = 24,
    Friendly9 = 25,
    Opposing9 = 26,
    Neutral9 = 27,
    Friendly10 = 28,
    Opposing10 = 29,
    Neutral10 = 30,
}

// SISO-REF-010-2023 Entity Kind [UID 7]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum EntityKind {
    #[default]
    Other = 0,
    Platform = 1,
    Munition = 2,
    LifeForm = 3,
    Environmental = 4,
    CulturalFeature = 5,
    Supply = 6,
    Radio = 7,
    Expendable = 8,
    SensorEmitter = 9,
}

// SISO-REF-010-2023 Other Kinds [UID 8]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum OtherKinds {
    #[default]
    Other = 0,
    Land = 1,
    Air = 2,
    Surface = 3,
    Subsurface = 4,
    Space = 5,
}

// SISO-REF-010-2023 Land Domain Categories [UID 9]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum LandDomainCategories {
    #[default]
    Other = 0,
    Tank = 1,
    ArmoredFightingVehicle,
    ArmoredUtilityVehicle,
    SelfPropelledArtillery,
    TowedArtillery,
    SmallWheeledUtilityVehicle,
    LargeWheeledUtilityVehicle,
    SmallTrackedUtilityVehicle,
    LargeTrackedUtilityVehicle,
    Mortar,
    MinePlow,
    MineRake,
    MineRoller,
    CargoTrailer,
    FuelTrailer,
    GeneratorTrailer,
    WaterTrailer,
    EngineerEquipment,
    HeavyEquipmentTransportTrailer,
    MaintenanceEquipmentTrailer,
    Limber,
    ChemicalDecontaminationTrailer,
    WarningSystem,
    TrainEngine,
    TrainCar,
    TrainCaboose,
    #[deprecated]
    CivilianVehicle,
    AirDefenseMissileDefenseUnitEquipment,
    C3ISystem,
    OperationsFacility,
    IntelligenceFacility,
    SurveillanceFacility,
    CommunicationsFacility,
    CommandFacility,
    C4IFacility,
    ControlFacility,
    FireControlFacility,
    MissileDefenseFacility,
    FieldCommandPost,
    ObservationPost,
    MineFlail = 41,
    Unmanned = 50,
    Motorcycle = 80,
    Car = 81,
    Bus,
    SingleUnitCargoTruck,
    SingleUnitUtilityEmergencyTruck,
    MultipleUnitCargoTruck,
    MultipleUnitUtilityEmergencyTruck,
    ConstructionSpecialtyVehicle,
    FarmSpecialtyVehicle,
    Trailer,
    Recreational,
    NonMotorized,
    Trains,
    UtilityEmergencyCar,
}

// SISO-REF-010-2023 Air Domain Categories [UID 10]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum AirDomainCategories {
    #[default]
    Other = 0,
    FighterAirDefense = 1,
    AttackStrike = 2,
    Bomber = 3,
    CargoTanker = 4,
    ASWPatrolObservation = 5,
    ElectronicWarfare = 6,
    Reconnaissance = 7,
    SurveillanceC2 = 8,
    AirSeaRescue = 9,
    AttackHelicopter = 20,
    UtilityHelicopter = 21,
    AntiSubmarineWarfarePatrolHelicopter = 22,
    CargoHelicopter = 23,
    ObservationHelicopter = 24,
    SpecialOperationsHelicopter = 25,
    TrainingHelicopter = 26,
    Trainer = 40,
    Unmanned = 50,
    NonCombatantCommercialAircraft = 57,
    CivilianUltralightAircraftNonrigidWing = 80,
    CivilianUltralightAircraftRigidWing = 81,
    CivilianFixedWingAircraftGlider = 83,
    CivilianFixedWingAircraftLightSport = 84,
    CivilianFixedWingAircraftSmall = 85,
    CivilianFixedWingAircraftMedium = 86,
    CivilianFixedWingAircraftLarge = 87,
    CivilianFixedWingAircraftHeavy = 88,
    CivilianHelicopterSmall = 90,
    CivilianHelicopterMedium = 91,
    CivilianHelicopterLarge = 92,
    CivilianAutogyro = 93,
    CivilianLighterthanAirBalloon = 100,
    CivilianLighterthanAirAirship = 101,
}

// SISO-REF-010-2023 Surface Domain Categories [UID 11]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum SurfaceDomainCategories {
    #[default]
    Other = 0,
    Carrier = 1,
    CommandShipCruiser = 2,
    GuidedMissileCruiser = 3,
    GuidedMissileDestroyer = 4,
    Destroyer = 5,
    GuidedMissileFrigate = 6,
    LightPatrolCraft = 7,
    MineCountermeasureShipCraft = 8,
    DockLandingShip = 9,
    TankLandingShip = 10,
    LandingCraft = 11,
    LightCarrier = 12,
    CruiserHelicopterCarrier = 13,
    Hydrofoil = 14,
    AirCushionSurfaceEffect = 15,
    Auxiliary = 16,
    AuxiliaryMerchantMarine = 17,
    Utility = 18,
    UnmannedSurfaceVehicle = 19,
    LittoralCombatShips = 20,
    SurveillanceShip = 21,
    Frigate = 50,
    Battleship = 51,
    HeavyCruiser = 52,
    DestroyerTender = 53,
    AmphibiousAssaultShip = 54,
    AmphibiousCargoShip = 55,
    AmphibiousTransportDock = 56,
    AmmunitionShip = 57,
    CombatStoresShip = 58,
    SurveillanceTowedArraySonarSystem = 59,
    FastCombatSupportShip = 60,
    NonCombatantShip = 61,
    CoastGuardCutters = 62,
    CoastGuardBoats = 63,
    FastAttackCraft = 64,
    InflatableBoat = 65,
    PassengerVessel = 80,
    DryCargoShip = 81,
    Tanker = 82,
    OffshoreSupportVessel = 83,
    PrivateMotorboat = 84,
    PrivateSailboat = 85,
    FishingVessel = 86,
    OtherVessels = 87,
    SearchandRescueVessels = 100,
    LifeSavingEquipment = 101,
}

// SISO-REF-010-2023 Subsurface Domain Categories [UID 12]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum SubsurfaceDomainCategories {
    #[default]
    Other = 0,
    SSBN = 1,
    SSGN = 2,
    SSN = 3,
    SSG = 4,
    SS = 5,
    SSAN = 6,
    SSA = 7,
    UnmannedUnderwaterVehicle = 8,
    SSB = 9,
    SSC = 10,
    SSP = 11,
    SSM = 12,
    SSNR = 13,
    SST = 14,
    AGSS = 15,
    SemiSubmersibleBoats = 16,
    CivilianSubmarines = 80,
    CivilianSubmersibles = 81,
    CivilianSemiSubmersibleBoats = 82,
}

// SISO-REF-010-2023 SpaceDomainCategories [UID 13]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum SpaceDomainCategories {
    #[default]
    Other = 0,
    MannedSpacecraft = 1,
    Unmanned = 2,
    Booster = 3,
    Debris = 10,
    SatelliteUnknownUnspecifiedMission = 11,
    SatelliteCommunication = 12,
    SatelliteNavigation = 13,
    SatelliteScienceExperimentalDemonstration = 14,
    SatelliteInert = 15,
    SatelliteEarthObservation = 16,
    SatelliteSpaceSurveillance = 17,
    SatelliteAstronomy = 18,
}

// SISO-REF-010-2023 MunitionKind [UID 14]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum MunitionKind {
    #[default]
    Other = 0,
    AntiAir = 1,
    AntiArmor = 2,
    AntiGuidedWeapon = 3,
    AntiRadar = 4,
    AntiSatellite = 5,
    AntiShip = 6,
    AntiSubmarine = 7,
    AntiPersonnel = 8,
    BattlefieldSupport = 9,
    Strategic = 10,
    Tactical = 11,
    DirectedEnergyWeapon = 12,
}

// SISO-REF-010-2023 MunitionCategory [UID 15]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum MunitionCategory {
    #[default]
    Other = 0,
    Guided = 1,
    Ballistic = 2,
    Fixed = 3,
}

// SISO-REF-010-2023 USWeaponSubcategories [UID 16]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
#[allow(non_camel_case_types)]
pub enum USWeaponSubcategories {
    #[default]
    AssaultmachinepistolKFAMP = 1,
    Automaticmodel1911A1_45 = 2,
    CombatMasterMarkVI_45Detronics = 3,
    DecockerKP90DC_45 = 4,
    DecockerKP91DC_40 = 5,
    GeneralofficersModel15_45 = 6,
    Nova9mmLaFrance = 7,
    PersonalDefenseWeaponMP5KPDW9mm = 8,
    SilencedColt_45LaFrance = 9,
    _5900series9mmSmithWessonSW = 10,
    M9 = 11,
    Model1911A1SpringfieldArmory = 12,
    Model20009mm = 13,
    P99mmSpringfieldArmory = 14,
    P129mm = 15,
    P85MarkII9mmRuger = 16,
    AdvancedCombatRifle5_56mmAAI = 17,
    CommandoassaultrifleModel7335_56mmColt = 18,
    InfantryrifleMini1420GB5_56mmRuger = 19,
    Mini145_56mmRuger = 20,
    MiniThirty7_62mmRuger = 21,
    Semiautomaticmodel82A2_50Barrett = 22,
    SniperWeaponSystemM247_62mm = 23,
    SnipingrifleM21SpringfieldArmory = 24,
    SnipingrifleM40A17_62mm = 25,
    SnipingrifleM6007_62mm = 26,
    AR15M165_56mm = 27,
    M1_30_1 = 28,
    M147_62mmNATO = 29,
    M14M1AM1A1A1SpringfieldArmory = 30,
    M14KassaultrifleLaFrance = 31,
    M16A2assaultrifle5_56mmColt = 32,
    M217_62mmU_S_ = 33,
    M77MarkII5_56mmRuger = 34,
    M77V7_62mmRuger = 35,
    S167_62x36mmGrendel = 36,
    SAR87_62mm = 37,
    SAR48007_62mm = 38,
    AssaultcarbineM16KLaFrance = 39,
    M1_30_2 = 40,
    M4Model7205_56mmColt = 41,
    M9009mmCalico = 42,
    AC556F5_56mmRuger = 43,
    M3_45 = 44,
    M11Cobray = 45,
    M9519mmCalico = 46,
    MP51010mm = 47,
    _9mmColt = 48,
    Ingram = 49,
    ExternallypoweredEPG7_62mmAres = 50,
    GECAL50 = 51,
    GeneralpurposeM607_62mm = 52,
    HeavyM2HBQCB_50RAMO = 53,
    LightassaultM60E3Enhanced7_62mm = 54,
    LightM16A25_56mmColt = 55,
    Light5_56mmAres = 56,
    LightweightM2_50RAMO = 57,
    LightweightassaultM60E37_62mm = 58,
    MinigunM1347_62mmGeneralElectric = 59,
    MGsystemMK19Mod340mm = 60,
    MGsystemorkitM2HBQCB_50SacoDefense = 61,
    M1919A4_30calBrowning = 62,
    _50calBrowning = 63,
    ColoredsmokehandgrenadeM18 = 64,
    ColoredsmokegrenadesFederalLaboratories = 65,
    InfraredsmokegrenadeM76 = 66,
    SmokehandgrenadeANM8HC = 67,
    DelayfragmentationhandgrenadeM61 = 68,
    DelayfragmentationhandgrenadeM67 = 69,
    ImpactfragmentationhandgrenadeM57 = 70,
    ImpactfragmentationhandgrenadeM68 = 71,
    IncendiaryhandgrenadeANM14TH3 = 72,
    LauncherIM20340mm = 73,
    LauncherM7940mm = 74,
    MultiplegrenadelauncherMM140mm = 75,
    MultishotportableflameweaponM202A266mm = 76,
    PortableABCM97 = 77,
    PortableM2A17 = 78,
    PortableM9E17 = 79,
    DragonmediumAntiArmormissileM47FGM77A = 80,
    JavelinAAWSM = 81,
    LightAntiTankWeaponM72LAWII = 82,
    RedeyeFIM43GeneralDynamics = 83,
    Saberdualpurposemissilesystem = 84,
    StingerFIM92GeneralDynamics = 85,
    TOWheavyAntiTankweapon = 86,
    BearTrapAPdevicePancor = 87,
    ChainGunautomaticweaponEX347_62mm = 88,
    CloseAssaultWeaponSystemCAWSAAI = 89,
    CAWSOlinHecklerandKoch = 90,
    CrossfireSAMModel88 = 91,
    DragonandM16 = 92,
    FiringportweaponM2315_56mmColt = 93,
    FoxholeDiggerExplosiveKitEXFODA = 94,
    InfantrySupportWeaponASP30RM30mm = 95,
    JackhammerMk3A2Pancor = 96,
    LightAntiArmorweaponM136AT4 = 97,
    M26A2 = 98,
    MasterKeyS = 99,
    Minigun5_56mm = 100,
    MultipurposeIndividualMunitionMPIMMarquardt = 101,
    MultipurposeweaponAT8 = 102,
    RecoillessrifleM40M40A2andM40A4106mm = 103,
    RecoillessrifleM6790mm = 104,
    RevolverSP101 = 105,
    RevolverSuperRedhawk_44magnumRuger = 106,
    RAWrocket140mmBrunswick = 107,
    RiflelauncherAntiArmorMunitionRAAMOlin = 108,
    RocketlauncherM203_5in = 109,
    RocketlauncherEnhancedM72EseriesHEAT66mm = 110,
    SelectivefireweaponAC5565_56mmRuger = 111,
    SelectivefireweaponAC556F5_56mmRuger = 112,
    ShotgunM870Mk1U_S_MarineCorpsRemington = 113,
    SMAWMk19383mmMcDonnellDouglas = 114,
    SMAWDDisposableSMAW = 115,
    SquadAutomaticWeaponSAWM2495_56mm = 116,
    TacticalSupportWeapon5012_50calPeregrine = 117,
    TelescopedAmmunitionRevolverGunTARG_50calAres = 118,
    UltimateoverundercombinationCiener = 119,
    M18A1Claymoremine = 120,
    Mortar81mm = 121,
    MachinegunM2407_62mm = 134,
}

// SISO-REF-010-2023 RussiaWeaponSubcategories [UID 17]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum RussiaWeaponSubcategories {
    #[default]
    Automatic9mmStechkin = 201,
    PSM5_45mm = 202,
    Selfloading9mmMakarov = 203,
    TT337_62mmTokarev = 204,
    AssaultrifleAKandAKM7_62mm = 205,
    AssaultrifleAK74andAKS745_45mm = 206,
    Selfloadingrifle7_62mmSimonov = 207,
    SniperrifleSVD7_62mmDragunov = 208,
    AKSU745_45mm = 209,
    PPS437_62mm = 210,
    PPSh417_62mm = 211,
    GeneralpurposePK7_62mm = 212,
    HeavyDShK38andModel384612_7mmDegtyarev = 213,
    HeavyNSV12_7mm = 214,
    LightRPD7_62mm = 215,
    LightRPK7_62mm = 216,
    LightRPK745_45mm = 217,
    HandgrenadeM75 = 218,
    HandgrenadeRGD5 = 219,
    APhandgrenadeF1 = 220,
    AThandgrenadeRKG3 = 221,
    AThandgrenadeRKG3M = 222,
    AThandgrenadeRKG3T = 223,
    FragmentationhandgrenadeRGN = 224,
    FragmentationhandgrenadeRGO = 225,
    SmokehandgrenadeRDG1 = 226,
    Plamyalauncher30mmAGS17 = 227,
    RiflemountedlauncherBG1540mm = 228,
    LPO50 = 229,
    ROKS3 = 230,
    CartmountedTPO50 = 231,
    GimletSA16 = 232,
    GrailSA7 = 233,
    GremlinSA14 = 234,
    SaggerAT3 = 235,
    SaxhornAT7 = 236,
    SpigotABAT14 = 237,
    SA18 = 238,
    SA19 = 239,
    Grad1Pmanportabletripodrocketlauncher122mm = 240,
    LightAntiArmorweaponRPG18 = 241,
    LightAntiTankweaponRPG22 = 242,
    MGRPG = 243,
    PortablerocketlauncherRPG16 = 244,
    Recoillessgun73mmSPG9 = 245,
    VATrocketlauncherRPG7 = 246,
    Mon50AntiPersonnelmine = 248,
    RPG29Vampir = 249,
    LaserDesignator = 250,
    AT4Spigot = 251,
    SA24IglaS = 252,
    Type69RPG = 253,
}

// SISO-REF-010-2023 UKWeaponSubcategories [UID 18]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum UKWeaponSubcategories {
    #[default]
    LAW80 = 1,
    Blowpipe = 2,
    Javelin = 3,
    _51mmmortar = 4,
    SLR7_62mmrifle = 5,
    Sterling9mmsubmachinegun = 6,
    L7A2generalpurposeMG = 7,
    L6WombatRecoillessrifle = 8,
    CarlGustav89mmrecoillessrifle = 9,
    SA80Individuallightsupportweapon = 10,
    Trigat = 11,
    MilanATmissile = 12,
}

// SISO-REF-010-2023 FrenchWeaponSubcategories [UID 19]
#[derive(Copy, Clone, Debug, Default, FromPrimitive, PartialEq)]
pub enum FrenchWeaponSubcategories {
    #[default]
    ACLSTRIM = 1,
    Mistralmissile = 2,
    MilanATmissile = 3,
    LRACF189mmATrocketlauncher = 4,
    FAMASrifle = 5,
    AA52machinegun = 6,
    _58mmriflegrenade = 7,
    FRF1sniperrifle = 8,
}
